#!/usr/bin/env osascript
# Returns the current playing song in Rdio for OS X.

tell application "Rdio"
  if player state is playing then
    set track_name to name of current track
    set artist_name to artist of current track
    set album_name to album of current track
    set now_playing to artist_name & " - " & track_name
    # Uncomment if Album name is wanted
    #set now_playing to now_playing & " - " & album_name
    end if
end tell

